# Generated by Django 2.1 on 2020-02-23 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pastemeapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paste',
            old_name='name',
            new_name='namess',
        ),
        migrations.RenameField(
            model_name='paste',
            old_name='textfield',
            new_name='textss_field',
        ),
    ]
