# Generated by Django 2.1 on 2020-02-23 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pastemeapp', '0002_auto_20200223_0829'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='paste',
            new_name='pasterDB',
        ),
    ]
